version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - fastapi_network

  fastapi:
    build:
      context: .
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - ENVIRONMENT=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - fastapi_network
    restart: always

volumes:
  redis_data:
  
networks:
  fastapi_network:
